from __future__ import annotations

from typing import Dict, List

from training.fechamentos.types import FechamentoSpec


SPECS: List[FechamentoSpec] = [
    FechamentoSpec(
        code="FC1",
        name="Fechamento Básico 17x15",
        total_numbers=17,
        game_size=15,
        games_count=4,
        fixed_required_count=0,
        guarantee_points=13,
        description="Modelo combinatório com 17 dezenas e 4 jogos de 15 (estatístico, sem garantia de prêmio).",
    ),
    FechamentoSpec(
        code="FC2",
        name="Fechamento 17x15 (8 jogos)",
        total_numbers=17,
        game_size=15,
        games_count=8,
        fixed_required_count=0,
        guarantee_points=14,
        description="Modelo combinatório com 17 dezenas e 8 jogos de 15 (estatístico, sem garantia de prêmio).",
    ),
    FechamentoSpec(
        code="FC3",
        name="Fechamento 17x15 (64 jogos)",
        total_numbers=17,
        game_size=15,
        games_count=64,
        fixed_required_count=0,
        guarantee_points=14,
        description="Modelo combinatório com 17 dezenas e 64 jogos de 15 (estatístico, sem garantia de prêmio).",
    ),
    FechamentoSpec(
        code="FC4",
        name="Fechamento 17x15 (40 jogos)",
        total_numbers=17,
        game_size=15,
        games_count=40,
        fixed_required_count=0,
        guarantee_points=13,
        description="Modelo combinatório com 17 dezenas e 40 jogos de 15 (estatístico, sem garantia de prêmio).",
    ),
    FechamentoSpec(
        code="FC34",
        name="Fechamento 17x15 com 8 fixas",
        total_numbers=17,
        game_size=15,
        games_count=4,
        fixed_required_count=8,
        guarantee_points=14,
        description="Modelo combinatório com 8 fixas e 4 jogos de 15 (estatístico, sem garantia de prêmio).",
    ),
    FechamentoSpec(
        code="FC5",
        name="Fechamento 18x15 (6 jogos)",
        total_numbers=18,
        game_size=15,
        games_count=6,
        fixed_required_count=0,
        guarantee_points=13,
        description="Modelo combinatório com 18 dezenas e 6 jogos de 15 (estatístico, sem garantia de prêmio).",
    ),
    FechamentoSpec(
        code="FC6",
        name="Fechamento 18x15 (24 jogos)",
        total_numbers=18,
        game_size=15,
        games_count=24,
        fixed_required_count=0,
        guarantee_points=14,
        description="Modelo combinatório com 18 dezenas e 24 jogos de 15 (estatístico, sem garantia de prêmio).",
    ),
    FechamentoSpec(
        code="FC35",
        name="Fechamento 18x15 com 3 fixas",
        total_numbers=18,
        game_size=15,
        games_count=18,
        fixed_required_count=3,
        guarantee_points=14,
        description="Modelo combinatório com 3 fixas e 18 jogos de 15 (estatístico, sem garantia de prêmio).",
    ),
    FechamentoSpec(
        code="FC36",
        name="Fechamento 18x16 com 3 fixas",
        total_numbers=18,
        game_size=16,
        games_count=7,
        fixed_required_count=3,
        guarantee_points=14,
        description="Modelo combinatório com 3 fixas e 7 jogos de 16 (estatístico, sem garantia de prêmio).",
    ),
    FechamentoSpec(
        code="FC37",
        name="Fechamento 18x15 com 6 fixas",
        total_numbers=18,
        game_size=15,
        games_count=11,
        fixed_required_count=6,
        guarantee_points=14,
        description="Modelo combinatório com 6 fixas e 11 jogos de 15 (estatístico, sem garantia de prêmio).",
    ),
    FechamentoSpec(
        code="FC73",
        name="Fechamento 18x16 (8 jogos)",
        total_numbers=18,
        game_size=16,
        games_count=8,
        fixed_required_count=0,
        guarantee_points=14,
        description="Modelo combinatório com 18 dezenas e 8 jogos de 16 (estatístico, sem garantia de prêmio).",
    ),
    FechamentoSpec(
        code="FC8",
        name="Fechamento 19x15 (4 jogos)",
        total_numbers=19,
        game_size=15,
        games_count=4,
        fixed_required_count=0,
        guarantee_points=12,
        description="Modelo combinatório com 19 dezenas e 4 jogos de 15 (estatístico, sem garantia de prêmio).",
    ),
    FechamentoSpec(
        code="FC9",
        name="Fechamento 19x15 (11 jogos)",
        total_numbers=19,
        game_size=15,
        games_count=11,
        fixed_required_count=0,
        guarantee_points=13,
        description="Modelo combinatório com 19 dezenas e 11 jogos de 15 (estatístico, sem garantia de prêmio).",
    ),
    FechamentoSpec(
        code="FC38",
        name="Fechamento 19x15 com 10 fixas",
        total_numbers=19,
        game_size=15,
        games_count=12,
        fixed_required_count=10,
        guarantee_points=13,
        description="Modelo combinatório com 10 fixas e 12 jogos de 15 (estatístico, sem garantia de prêmio).",
    ),
    FechamentoSpec(
        code="FC39",
        name="Fechamento 19x15 com 10 fixas",
        total_numbers=19,
        game_size=15,
        games_count=9,
        fixed_required_count=10,
        guarantee_points=14,
        description="Modelo combinatório com 10 fixas e 9 jogos de 15 (estatístico, sem garantia de prêmio).",
    ),
    FechamentoSpec(
        code="FC40",
        name="Fechamento 19x15 com 6 fixas",
        total_numbers=19,
        game_size=15,
        games_count=34,
        fixed_required_count=6,
        guarantee_points=14,
        description="Modelo combinatório com 6 fixas e 34 jogos de 15 (estatístico, sem garantia de prêmio).",
    ),
    FechamentoSpec(
        code="FC41",
        name="Fechamento 19x15 com 4 fixas",
        total_numbers=19,
        game_size=15,
        games_count=55,
        fixed_required_count=4,
        guarantee_points=14,
        description="Modelo combinatório com 4 fixas e 55 jogos de 15 (estatístico, sem garantia de prêmio).",
    ),
    FechamentoSpec(
        code="FC42",
        name="Fechamento 19x15 com 12 fixas",
        total_numbers=19,
        game_size=15,
        games_count=35,
        fixed_required_count=12,
        guarantee_points=15,
        description="Modelo combinatório com 12 fixas e 35 jogos de 15 (estatístico, sem garantia de prêmio).",
    ),
    FechamentoSpec(
        code="FC43",
        name="Fechamento 19x15 com 13 fixas",
        total_numbers=19,
        game_size=15,
        games_count=15,
        fixed_required_count=13,
        guarantee_points=15,
        description="Modelo combinatório com 13 fixas e 15 jogos de 15 (estatístico, sem garantia de prêmio).",
    ),
    FechamentoSpec(
        code="FC44",
        name="Fechamento 19x15 com 11 fixas",
        total_numbers=19,
        game_size=15,
        games_count=70,
        fixed_required_count=11,
        guarantee_points=15,
        description="Modelo combinatório com 11 fixas e 70 jogos de 15 (estatístico, sem garantia de prêmio).",
    ),
]


SPEC_BY_CODE: Dict[str, FechamentoSpec] = {spec.code: spec for spec in SPECS}


__all__ = ["SPECS", "SPEC_BY_CODE"]
