from __future__ import annotations

from typing import Dict, List

from training.fechamentos_posicionais.types import FechamentoPosicionalSpec


SPECS: List[FechamentoPosicionalSpec] = [
    FechamentoPosicionalSpec(
        code="FC93",
        name="Posicional 20 dezenas (5 grupos de 2)",
        total_numbers=20,
        game_size=15,
        games_count=10,
        fixed_required_count=10,
        guarantee_points_declared=14,
        group_distribution=[2, 2, 2, 2, 2],
        description="Fechamento posicional com 20 dezenas, 10 fixas e 5 grupos de 2 (estatístico, sem garantia de prêmio).",
    ),
    FechamentoPosicionalSpec(
        code="FC94",
        name="Posicional 20 dezenas (5 grupos de 4)",
        total_numbers=20,
        game_size=15,
        games_count=80,
        fixed_required_count=0,
        guarantee_points_declared=15,
        group_distribution=[4, 4, 4, 4, 4],
        description="Fechamento posicional com 20 dezenas e 5 grupos de 4 (estatístico, sem garantia de prêmio).",
    ),
    FechamentoPosicionalSpec(
        code="FC92",
        name="Posicional 20 dezenas (1 grupo de 15)",
        total_numbers=20,
        game_size=15,
        games_count=95,
        fixed_required_count=5,
        guarantee_points_declared=14,
        group_distribution=[15],
        description="Fechamento posicional com 20 dezenas, 5 fixas e 1 grupo de 15 (estatístico, sem garantia de prêmio).",
    ),
    FechamentoPosicionalSpec(
        code="FC91",
        name="Posicional 20 dezenas (1 grupo de 16)",
        total_numbers=20,
        game_size=15,
        games_count=273,
        fixed_required_count=4,
        guarantee_points_declared=14,
        group_distribution=[16],
        description="Fechamento posicional com 20 dezenas, 4 fixas e 1 grupo de 16 (estatístico, sem garantia de prêmio).",
    ),
    FechamentoPosicionalSpec(
        code="FC78",
        name="Posicional 20 dezenas (3 grupos de 5)",
        total_numbers=20,
        game_size=15,
        games_count=3,
        fixed_required_count=5,
        guarantee_points_declared=15,
        group_distribution=[5, 5, 5],
        description="Fechamento posicional com 20 dezenas, 5 fixas e 3 grupos de 5 (estatístico, sem garantia de prêmio).",
    ),
    FechamentoPosicionalSpec(
        code="FC76",
        name="Posicional 20 dezenas (4 grupos de 5)",
        total_numbers=20,
        game_size=15,
        games_count=4,
        fixed_required_count=0,
        guarantee_points_declared=15,
        group_distribution=[5, 5, 5, 5],
        description="Fechamento posicional com 20 dezenas e 4 grupos de 5 (estatístico, sem garantia de prêmio).",
    ),
    FechamentoPosicionalSpec(
        code="FC84",
        name="Posicional 19 dezenas (4 grupos de 4)",
        total_numbers=19,
        game_size=15,
        games_count=4,
        fixed_required_count=3,
        guarantee_points_declared=15,
        group_distribution=[4, 4, 4, 4],
        description="Fechamento posicional com 19 dezenas, 3 fixas e 4 grupos de 4 (estatístico, sem garantia de prêmio).",
    ),
    FechamentoPosicionalSpec(
        code="FC86",
        name="Posicional 19 dezenas (7 grupos de 2)",
        total_numbers=19,
        game_size=15,
        games_count=14,
        fixed_required_count=5,
        guarantee_points_declared=14,
        group_distribution=[2, 2, 2, 2, 2, 2, 2],
        description="Fechamento posicional com 19 dezenas, 5 fixas e 7 grupos de 2 (estatístico, sem garantia de prêmio).",
    ),
    FechamentoPosicionalSpec(
        code="FC87",
        name="Posicional 19 dezenas (1 grupo de 13)",
        total_numbers=19,
        game_size=15,
        games_count=34,
        fixed_required_count=6,
        guarantee_points_declared=14,
        group_distribution=[13],
        description="Fechamento posicional com 19 dezenas, 6 fixas e 1 grupo de 13 (estatístico, sem garantia de prêmio).",
    ),
    FechamentoPosicionalSpec(
        code="FC129",
        name="Posicional 19 dezenas (9 grupos de 2)",
        total_numbers=19,
        game_size=15,
        games_count=36,
        fixed_required_count=1,
        guarantee_points_declared=15,
        group_distribution=[2, 2, 2, 2, 2, 2, 2, 2, 2],
        description="Fechamento posicional com 19 dezenas, 1 fixa e 9 grupos de 2 (estatístico, sem garantia de prêmio).",
    ),
    FechamentoPosicionalSpec(
        code="FC88",
        name="Posicional 19 dezenas (7 grupos de 2)",
        total_numbers=19,
        game_size=15,
        games_count=70,
        fixed_required_count=5,
        guarantee_points_declared=15,
        group_distribution=[2, 2, 2, 2, 2, 2, 2],
        description="Fechamento posicional com 19 dezenas, 5 fixas e 7 grupos de 2 (estatístico, sem garantia de prêmio).",
    ),
    FechamentoPosicionalSpec(
        code="FC130",
        name="Posicional 19 dezenas (8 grupos de 2)",
        total_numbers=19,
        game_size=15,
        games_count=28,
        fixed_required_count=3,
        guarantee_points_declared=15,
        group_distribution=[2, 2, 2, 2, 2, 2, 2, 2],
        description="Fechamento posicional com 19 dezenas, 3 fixas e 8 grupos de 2 (estatístico, sem garantia de prêmio).",
    ),
    FechamentoPosicionalSpec(
        code="FC85",
        name="Posicional 18 dezenas (1 grupo de 10)",
        total_numbers=18,
        game_size=15,
        games_count=56,
        fixed_required_count=8,
        guarantee_points_declared=15,
        group_distribution=[10],
        description="Fechamento posicional com 18 dezenas, 8 fixas e 1 grupo de 10 (estatístico, sem garantia de prêmio).",
        condition_text=(
            "Condição de garantia: acertando exatamente 5 das 8 fixas escolhidas e as 10 dezenas do grupo, "
            "atinge 15 pontos (modelo combinatório)."
        ),
    ),
    FechamentoPosicionalSpec(
        code="FC80",
        name="Posicional 18 dezenas (1 grupo de 13)",
        total_numbers=18,
        game_size=15,
        games_count=286,
        fixed_required_count=5,
        guarantee_points_declared=15,
        group_distribution=[13],
        description="Fechamento posicional com 18 dezenas, 5 fixas e 1 grupo de 13 (estatístico, sem garantia de prêmio).",
    ),
    FechamentoPosicionalSpec(
        code="FC81",
        name="Posicional 18 dezenas (1 grupo de 14)",
        total_numbers=18,
        game_size=15,
        games_count=364,
        fixed_required_count=4,
        guarantee_points_declared=15,
        group_distribution=[14],
        description="Fechamento posicional com 18 dezenas, 4 fixas e 1 grupo de 14 (estatístico, sem garantia de prêmio).",
    ),
    FechamentoPosicionalSpec(
        code="FC82",
        name="Posicional 18 dezenas (1 grupo de 15)",
        total_numbers=18,
        game_size=15,
        games_count=455,
        fixed_required_count=3,
        guarantee_points_declared=15,
        group_distribution=[15],
        description="Fechamento posicional com 18 dezenas, 3 fixas e 1 grupo de 15 (estatístico, sem garantia de prêmio).",
    ),
    FechamentoPosicionalSpec(
        code="FC128",
        name="Posicional 17 dezenas (8 grupos de 2)",
        total_numbers=17,
        game_size=15,
        games_count=8,
        fixed_required_count=1,
        guarantee_points_declared=15,
        group_distribution=[2, 2, 2, 2, 2, 2, 2, 2],
        description="Fechamento posicional com 17 dezenas, 1 fixa e 8 grupos de 2 (estatístico, sem garantia de prêmio).",
        condition_text=(
            "Este fechamento tem 2 garantias declaradas: (1) acertando a fixa + 7 grupos de variáveis, "
            "atinge 15 pontos; (2) acertando as 15 dezenas do resultado entre 8 grupos, mínimo de 14 pontos "
            "(modelo combinatório)."
        ),
    ),
]


SPEC_BY_CODE: Dict[str, FechamentoPosicionalSpec] = {spec.code: spec for spec in SPECS}


__all__ = ["SPECS", "SPEC_BY_CODE"]
